version: "3.8"

services:

  db:
    image: postgres:15
    container_name: library-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: library-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/librarydb
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: